schema_version = 1
max_ranked_results = 10

[evolution]
population_size = 24
generation_limit = 12
num_individuals_per_parents = 2
selection_ratio = 0.7
mutation_rate = 0.35
reinsertion_ratio = 0.75

[plotting]
output_dir = "../output"
